// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY82v-PtfEfbJ1vL6kVYaLekdLyVRpFDU',
    appId: '1:999005566436:web:bfbfac3c6ccb9b93c5c3f1',
    messagingSenderId: '999005566436',
    projectId: 'socialmediaapp-b1d3a',
    authDomain: 'socialmediaapp-b1d3a.firebaseapp.com',
    databaseURL: 'https://socialmediaapp-b1d3a-default-rtdb.firebaseio.com',
    storageBucket: 'socialmediaapp-b1d3a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFR_inudKQ2YMRAY2KVCpF5c-tErhANso',
    appId: '1:999005566436:android:7aa5291395f8faeec5c3f1',
    messagingSenderId: '999005566436',
    projectId: 'socialmediaapp-b1d3a',
    databaseURL: 'https://socialmediaapp-b1d3a-default-rtdb.firebaseio.com',
    storageBucket: 'socialmediaapp-b1d3a.appspot.com',
  );
}
